import type { ApplicationFormInput } from '@/lib/application-form/schema';

/** A complete application form, every section filled — long Thai values included. Override per test. */
export function applicationFormInput(overrides: Partial<ApplicationFormInput> = {}): ApplicationFormInput {
  return {
    locale: 'th',
    letterhead: 'SHD',
    positionOther: 'เจ้าหน้าที่บัญชีลูกหนี้',
    expectedSalaryMin: 25000,
    expectedSalaryMax: 30000,
    nameTh: 'นางสาวสุภาวดี ศรีสุข',
    nameEn: 'Supawadee Srisuk',
    nickname: 'ปุ้ย',
    gender: 'FEMALE',
    address: {
      houseNo: '99/123',
      moo: '4',
      soi: 'ลาดพร้าว 101 แยก 3',
      road: 'ลาดพร้าว',
      subdistrict: 'คลองจั่น',
      district: 'บางกะปิ',
      province: 'กรุงเทพมหานคร',
      postalCode: '10240',
    },
    homePhone: '02-123-4567',
    mobile: '081-234-5678',
    email: 'supawadee.srisuk@example.com',
    birthDate: '1998-05-12',
    nationality: 'ไทย',
    sensitiveConsent: true,
    sensitive: { ethnicity: 'ไทย', religion: 'พุทธ', bloodType: 'O', weightKg: 52, heightCm: 160 },
    family: {
      fatherName: 'นายสมศักดิ์ ศรีสุข',
      fatherOccupation: 'ค้าขาย',
      motherName: 'นางมาลี ศรีสุข',
      motherOccupation: 'ทำนาข้าว น้ำตาล',
      siblings: 3,
      birthOrder: 2,
    },
    marriage: { status: 'SINGLE', spouseName: '', spouseMaidenName: '', children: null, spouseWorkplace: '' },
    military: null,
    education: [
      {
        level: 'SECONDARY',
        institute: 'โรงเรียนเตรียมอุดมศึกษาน้อมเกล้า',
        country: 'ไทย',
        gpa: '3.45',
        major: 'วิทย์-คณิต',
        graduationYear: '2559',
      },
      {
        level: 'DEGREE',
        institute: 'จุฬาลงกรณ์มหาวิทยาลัย',
        country: 'ไทย',
        gpa: '3.21',
        major: 'บัญชีบัณฑิต',
        graduationYear: '2563',
      },
    ],
    skills: {
      language: 'อังกฤษ',
      speak: 'GOOD',
      read: 'EXCELLENT',
      write: 'GOOD',
      typingThWpm: 45,
      typingEnWpm: 40,
      computer: 'Microsoft Excel (Pivot, VLOOKUP), Word, PowerPoint, SAP B1, Express',
      motorcycleLicense: true,
      carLicense: false,
    },
    currentJob: {
      company: 'บริษัท ตัวอย่างการค้า จำกัด',
      position: 'เจ้าหน้าที่บัญชี',
      duties: 'บันทึกบัญชีลูกหนี้ ออกใบแจ้งหนี้ ติดตามการชำระเงิน กระทบยอดธนาคารประจำเดือน',
      from: '2021-06',
      to: '',
      lastSalary: '22,000',
      otherIncome: '2,000',
      totalIncome: '24,000',
      benefits: 'ประกันสังคม ประกันกลุ่ม โบนัส',
      reasonForLeaving: 'ต้องการความก้าวหน้า',
    },
    previousJob: {
      company: 'ห้างหุ้นส่วนจำกัด ทดสอบ',
      position: 'ผู้ช่วยบัญชี',
      from: '2020-07',
      to: '2021-05',
      lastSalary: '15,000',
      reasonForLeaving: 'สัญญาจ้างสิ้นสุด',
    },
    emergency: { name: 'นางมาลี ศรีสุข', relationship: 'มารดา', phone: '089-765-4321' },
    certified: true,
    ...overrides,
  };
}
